name: 'Zola Deploy to Pages with HTML minification'
description: 'Build and deploy a Zola site to GitHub Pages and minify all HTML files'
author: 'Pranit Bauva'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'zap'  
  color: 'green'
